{"name": "test_", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_1.Test_one object at 0x0000016CE55AA780>\n\n    def test_(self):\n        print(555555555555)\n>       assert False\nE       assert False\n\ntest_1.py:15: AssertionError"}, "attachments": [{"name": "stdout", "source": "3741ab18-b307-46ed-b6f8-5a8f047e9650-attachment.txt", "type": "text/plain"}], "start": 1684556743300, "stop": 1684556743301, "uuid": "2d20ae27-48ae-45a9-b365-3b4fab6272b5", "historyId": "a733d0aaca55ecc01d221222d8c97aef", "testCaseId": "f6dec92c9920031710ca6950d3af7c8d", "fullName": "test_1.Test_one#test_", "labels": [{"name": "suite", "value": "test_1"}, {"name": "subSuite", "value": "Test_one"}, {"name": "host", "value": "DESKTOP-Q81OJ6P"}, {"name": "thread", "value": "22288-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_1"}]}